# Generated by Django 6.0.3 on 2026-06-07 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_shipping_city_order_shipping_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company/Seller who owns this product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('company', 'Company/Seller')], default='customer', max_length=20),
        ),
    ]
